### ISSUE TITLE
Stock level of Products with type Selection Clears shortly after creation

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#360]
**Environment**
1. Version 2020.10
2. Operating system Linux Cent OS 7

**Describe the bug**
Stock level of Products with type Selection Clears shortly after creation

**To Reproduce**
1. Create a product with type: Selection
2. Go To Tab Variants
3. set Stock level for all Variants and click save
4. after refresh the page all stock levels  are recorded correctly
5. but after some minutes if refresh the page all stock levels clears and in the front-end when customers select that variant to add to basket they see the message the selected product is no longer available

**Screenshots**
![stock_levels](https://user-images.githubusercontent.com/16049244/105310120-5c9d3b00-5bd2-11eb-8a6e-3c5953530ea2.jpg)

Why does this happen?

**Comment by aimeos** [comment]
Can you please find out more when and why the stock levels are removed?

**Comment by aimeos** [comment]
Any news?

**Comment by parsester** [comment]
i was trying to figure out what happens when stock levels are removed, but i have no idea about this, just i know after a while (from a few seconds to a few minutes) after save the product when i go back to edit the product i see that stock levels have been removed.

**Comment by aimeos** [comment]
Unfortunately, that's not helpful especially as the problem doesn't occur in a standard setup and it must be related to your own code.

**Comment by parsester** [comment]
> Can you please find out more when and why the stock levels are removed?
> Unfortunately, that's not helpful especially as the problem doesn't occur in a standard setup and it must be related to your own code.

I tried different situations to find out how this happens and finally I realized that this happen when we create a new selection type product from exist product, and after we save copied product sock-levels of exist product will be deleted.

for copy product we use 2 way:
first we click on the "copy this entry" icon of exist selection type product in the product's list, change entries and click on the save button.
second we create a new selection type product and instead of clicking on the save button use the "Save & Copy" button to create a copy of new product.

in both of this ways stock-levels of the exist selection type product that we make a copy from that clear after saving the new product.

for better understand this happening i upload 2 video for 2 ways of copy and attach links here:

Save & Copy: [https://gofile.io/d/aqK5jn](url)
Copy This Entry: [https://gofile.io/d/iIgzPh](url)

**Comment by aimeos** [comment]
This is a problem when copying products because the stock levels are referenced by the SKU, not the product ID and they are moved to the newly created product. It's a principle problem that is solved in dev-master and will be part of 2020.04+ because there the stock entries are referenced by product IDs now. In 2020.10, better don't use the copy feature for selection products.

**Comment by parsester** [comment]
> This is a problem when copying products because the stock levels are referenced by the SKU, not the product ID and they are moved to the newly created product. It's a principle problem that is solved in dev-master and will be part of 2020.04+ because there the stock entries are referenced by product IDs now. In 2020.10, better don't use the copy feature for selection products.

hello again dear aimeos, after January I still have this problem, you say the problem solved in dev-master and will be part of 2020.04+ and now i update my packages and now use aimeos/ai-admin-jqadm 2020.10.23, but still I have that problem and when I copy from selection product and make changes and save it, after a while all stock-levels was cleared, what can I do?

**Comment by aimeos** [comment]
Sorry, the correct version with the change is **2021.04+** not _2020.04+_

**Comment by aimeos** [comment]
Yes, upgrading is possible but check for the breaking changes:
https://aimeos.org/docs/latest/changelog/2021.x/
