### ISSUE TITLE
Laravel auth View error

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#458]
**Environment**
1. Version (e.g. dev- master)
2. Operating system (Linux, Mac, Windows)

****
PageController overide all Laravel auth routes to /page.index.blade,
---
rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /xxx/aimeos-laravel/src/default.php on line 75

**Comment by aimeos** [comment]
This has been fixed in dev-master and 2022.04 now. The page routes have changed (added "/p/" segment so Laravel is able to distingish between these routes).

The rtrim() problem is due to a missing `ASSET_URL` in your `.env` file. If `ASSET_URL` is not available, `APP_URL` will be used as fallback now.

**Comment by Cyber-Devs** [comment]
After composer up as Aimeos:clear optimize:clear but the same responce, even I deleted vendor folder and reinstalled but The problem is still there... every Laravel route override by PageController, and routes didn't adopted /p/ segment..

**Comment by aimeos** [comment]
You have to update your ./config/shop.php and ./routes/web.php because they are copied initially but not updated after first installation any more:
* https://github.com/aimeos/aimeos/blob/master/config/shop.php#L8-L42
* https://github.com/aimeos/aimeos/blob/master/routes/web.php#L16-L42

**Comment by Cyber-Devs** [comment]
login route is resolve but now error Route [aimeos_home] not defined.

**Comment by Cyber-Devs** [comment]
resolved...
